network.host: 0.0.0.0
http.port: 9200
transport.host: localhost
transport.tcp.port: 9300

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1
# bootstrap.memory_lock: true
xpack.ml.enabled: false

node.master: true
node.ingest: true
node.data: true

discovery.type: "single-node"