#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="elasticsearch"

declare -a es_opts

while IFS='=' read -r envvar_key envvar_value
	do
	# Elasticsearch env vars need to have at least two dot separated lowercase words, e.g. `cluster.name`
		if [[ "$envvar_key" =~ ^[a-z0-9_]+\.[a-z0-9_]+ ]]; then
			if [[ ! -z $envvar_value ]]; then
				es_opt="-E${envvar_key}=${envvar_value}"
				es_opts+=("${es_opt}")
			fi
		fi
done < <(env)


print_info "Starting Elasticsearch ${ELASTICSEARCH_VERSION}"
sudo -Eu elasticsearch elasticsearch ${es_opts[@]}
