version: '2.4'

services:
  elasticsearch-app:
    image: tiredofit/elasticsearch
    container_name: elasticsearch-app
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
    environment:
      - CONTAINER_NAME=elasticsearch-app
    networks:
      - services
    restart: always

networks:
  services:
    external: true
